site_name: BERTopic
extra_css: [style.css]
repo_url: https://github.com/MaartenGr/BERTopic
site_url: https://maartengr.github.io/BERTopic/
site_description: Leveraging BERT and a class-based TF-IDF to create easily interpretable topics.
site_author: Maarten P. Grootendorst
use_directory_urls: false
nav:
  - Home: index.md
  - The Algorithm: tutorial/algorithm/algorithm.md
  - Guides:
      - Getting Started: tutorial/quickstart/quickstart.md
      - Embedding Models: tutorial/embeddings/embeddings.md
      - Topic Visualization: tutorial/visualization/visualization.md
      - Topic Reduction: tutorial/topicreduction/topicreduction.md
      - Topic Representation: tutorial/topicrepresentation/topicrepresentation.md
      - Search Topics: tutorial/search/search.md
      - Custom Sub-Models: tutorial/models/models.md
      - Dynamic Topic Modeling: tutorial/topicsovertime/topicsovertime.md
  - API:
      - BERTopic: api/bertopic.md
      - cTFIDF: api/ctfidf.md
      - MMR: api/mmr.md
  - FAQ: faq.md
  - Changelog: changelog.md
plugins:
  - mkdocstrings:
      watch:
        - bertopic
  - search
copyright: Copyright &copy; 2020 Maintained by <a href="https://github.com/MaartenGr">Maarten</a>.
theme:
  custom_dir: images/
  name: material
  icon:
    logo: material/library
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: icon.png
  logo: icon_white.png
  feature:
    tabs: true
  palette:
    primary: black
    accent: grey
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
